### ISSUE TITLE
16MP is new Google "free" limit.  Should app now compress to just below this?

### ISSUE THREAD

**Issue by mgillespie** [leocrawford/picasawebsync#29]
At this years Google I/O, it was announced that Google are now offering free, unlimited storage for all pictures UNDER 16MP.  

Currently the resize option scales it the old way (2048 horizontal pixels).  Should this be now made smarter and work out the MP and resize if it's above 16MP?

**Comment by leocrawford** [comment]
I'm intrigued by this. It's hard to figure out from the publicly available info whether you reduce the size to 16MP (and what that even means) or whether if your account is registered as "free" that all uploaded content is transformed on upload.  It seems that even images less than 16MP have lossy compression applied for the free service, so I suspect the latter. 

I'm happy to make a code change if someone can actually figure out what the rules are and how they're applied.

**Comment by Webreaper** [comment]
From what I understand, unless you’re uploading to a feed where imgmax=d, the image will be scaled. One would assume that they have a combination of pixel dimension and file size limits, and anything over those sizes will have the lossy compression applied unless you have paid storage and explicitly specify original size uploads.

I’m interested due to my own picasawebsync client (here https://github.com/Webreaper/PicasawebSync <https://github.com/Webreaper/PicasawebSync>) although being a sync client, I’m only interested in full-res images; I haven’t added any option to shrink images to the smaller size. That said, if the source images are low enough res (and my supposition above is correct) then it would’t matter.



On 21 Jun 2015, at 20:14, Leo Crawford <notifications@github.com> wrote:

I'm intrigued by this. It's hard to figure out from the publicly available info whether you reduce the size to 16MP (and what that even means) or whether if your account is registered as "free" that all uploaded content is transformed on upload. It seems that even images less than 16MP have lossy compression applied for the free service, so I suspect the latter.

I'm happy to make a code change if someone can actually figure out what the rules are and how they're applied.

**Comment by mgillespie** [comment]
Are we saying that you don't need to resize the photos at all if you have selected the option of unlimited photo storage on your account?

I guess this is less flexible, as it means it's an all or nothing arrangement, you can't keep those special pics at full resolution, and the rest of them compressed to "16MP".   But then that's what FlickR is for..

Can anyone confirm that they have uploaded large amounts of data with this client WITHOUT the resize option, and it didn't touch their free storage amount?  if so, that would confirm server-size compression/scaling.

**Comment by ManuCart** [comment]
I just trying to upload photos without --shrink and photos are all under 16MP.
Google not doing resize and coutdown space storage.
The high quality is check under parameters in google photos.
Maybe it's only avalaible with google official app from android.

**Comment by mgillespie** [comment]
So are you saying if you upload via the Picasa API, you are restricted to the 2048 horizontal size restriction, but if you upload via the Photos official app, it just resizes your pictures serverside to 16MP?

**Comment by Webreaper** [comment]
I’m uploading using my java app, which uses the API, at full resolution (jpegs up to 10-12MB) and they don’t get resized. Obviously, though, that eats into my storage allowance, but that’s what I pay for. :)

On 26 Jun 2015, at 13:11, Mark Gillespie <notifications@github.com> wrote:

So are you saying if you upload via the Picasa API, you are restricted to the 2048 horizontal size restriction, but if you upload via the Photos official app, it just resizes your pictures serverside to 16MP?

**Comment by ManuCart** [comment]
Yes I'm sure for the Picasa API, because I just trying today with a new google account. But I'm not tried with the Android app Google Photos. But this is what I understood.

**Comment by leocrawford** [comment]
It seems that this isn't well defined, and it will take a little experimentation to know for sure how google treats image size.

**Comment by leocrawford** [comment]
I'm going to close this for now, until/unless someone is able to confirm exactly how google treats thus
